-keepclassmembers class me.aravi.instagramx.models* { *; }
-keepclassmembers class me.aravi.instagramx.models.allposts* { *; }
-keepclassmembers class me.aravi.instagramx.models.post* { *; }
-keepclassmembers class me.aravi.instagramx.models.profile* { *; }
-flattenpackagehierarchy